### ISSUE TITLE
FSRS Version

### ISSUE THREAD

**Issue by jfmamjjasond123** [open-spaced-repetition/swift-fsrs#10]
What version of FSRS is used with the swift code?

**Comment by L-M-Sherlock** [comment]
FSRSv4

**Comment by jfmamjjasond123** [comment]
Any plans to update the swift version?

**Comment by L-M-Sherlock** [comment]
Please ask @bensmiley

**Comment by tomerbeil** [comment]
@bensmiley Hi!

First of all, thank you for developing the Swift version of FSRS. It’s been incredibly useful! I am curious about the future development plans for this project. Specifically, are there any updates planned to bring FSRS to version 4.5? Looking forward to any information you might have!

Thank you!

**Comment by aehlke** [comment]
The better approach may be to wrap the rust library into an SPM module.

**Comment by bensmiley** [comment]
> @bensmiley Hi!
> 
> First of all, thank you for developing the Swift version of FSRS. It’s been incredibly useful! I am curious about the future development plans for this project. Specifically, are there any updates planned to bring FSRS to version 4.5? Looking forward to any information you might have!
> 
> Thank you!

HI @tomerbeil I will probably update the code at some point. But given it's a translation from a different language, that can be quite a difficult process because it requires me to identify every place where the code has been modified and then find that place in the Swift code and apply the modification. 

The FSRS project is still quite young so my feeling would be to wait until it's more mature and then do the update work. In the meantime maybe the approach suggested by @aehlke would work. 

I have limited time so help would be welcome. If you were to submit a pull request with updates I would prioritise merging it.

**Comment by SplittyDev** [comment]
@bensmiley I've submitted a PR to update everything to FSRS 4.5, and tested using the same parameters as the Go version, achieving the same output.
